# Generated by Django 5.2.15 on 2026-07-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_summarized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
