# Generated by Django 5.2.15 on 2026-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_document_is_summarized_document_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[("pdf", "PDF"), ("docx", "DOCX"), ("txt", "TXT")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
