# Generated by Django 5.2.15 on 2026-07-14 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
